project_name = "llm_example

server = ''                   
database = ''          
schema = ''
table = ''  

# Here we describe where the output and logs are saved, change as necessary
output_dir = ''
log_dir = '' 
